set_property PACKAGE_PIN R15 [get_ports A]
set_property PACKAGE_PIN R17 [get_ports B]
set_property PACKAGE_PIN T18 [get_ports Bin]
set_property PACKAGE_PIN V11 [get_ports Diff]
set_property PACKAGE_PIN V12 [get_ports Bout]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports Bin]
set_property IOSTANDARD LVCMOS33 [get_ports Diff]
set_property IOSTANDARD LVCMOS33 [get_ports Bout]

