# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/viv_lab5/.Xil/Vivado-4960-ABDUL-MANAN/incrSyn}
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/viv_lab5/viv_lab5.cache/wt} [current_project]
set_property parent.project_path {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/viv_lab5/viv_lab5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {u:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/viv_lab5/viv_lab5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/decoder.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/decoder_1.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/decoder_2.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/full_adder.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/log_shifter_4bit.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/multiplier_c3.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/mux2to1.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/rca_4bit.sv}
  {U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/SRC/top_lab5.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/viv_lab5/viv_lab5.srcs/constrs_1/new/lab5.xdc}}
set_property used_in_implementation false [get_files {{U:/GITHUB projects/UET-Core-Programming/Semester_03/DLD_LAB/lab_5/viv_lab5/viv_lab5.srcs/constrs_1/new/lab5.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_lab5 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_lab5.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_lab5_utilization_synth.rpt -pb top_lab5_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
